services:
  - type: web
    name: saitekikanri
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn myproject.wsgi --log-file
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "myproject.settings"
      - key: SECRET_KEY
        value: "django-insecure-*ntxz!=yyyp!_^o0yrj2^!ltwe9-$$#ug8i=0-3o%$(5-$7b47"
